### ISSUE TITLE
Waystone recipe errors on startup

### ISSUE THREAD

**Issue by andrebarks** [SwanX1/SlightlyVanillaFlavoured#8]
When I start up the server, I get the following error messages in the server-console, they seem to correlate to issues with the waystones mods and it's recipes.

Pack-Version: 2.2.0 (`Slightly_Vanilla_Flavoured-2.2.0-SERVER-PACK`) 
Downloaded from Curseforge
```
[23:45:39] [Worker-Main7/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file waystones:bound_scroll from waystones:recipes/bound_scroll.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:495) ~[?:?] {re:classloading}
        at net.minecraft.util.JSONUtils.func_193839_a(SourceFile:532) ~[?:?] {re:classloading}
        at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:48) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
        at net.minecraft.client.resources.JsonReloadListener.func_212854_a_(JsonReloadListener.java:22) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
        at net.minecraft.client.resources.ReloadListener.func_215270_b(SourceFile:11) ~[?:?] {re:computing_frames,re:classloading,re:mixin}
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) [?:1.8.0_271] {}
        at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) [?:1.8.0_271] {re:computing_frames}
        at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) [?:1.8.0_271] {}
Caused by: java.io.EOFException: End of input at line 1 column 1 path $
        at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1393) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.stream.JsonReader.peek(JsonReader.java:425) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:716) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:910) ~[server-1.16.5-20210115.111550-extra.jar:?] {}
        at net.minecraft.util.JSONUtils.func_188173_a(SourceFile:493) ~[?:?] {re:classloading}
        ... 10 more
[
(Skipping a bunch of more recipes, all recipes from the Waystone mod)
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
[23:45:39] [Worker-Main7/ERROR] [minecraft/JsonReloadListener]: Couldn't parse data file waystones:waystone from waystones:recipes/waystone.json
com.google.gson.JsonParseException: java.io.EOFException: End of input at line 1 column 1 path $
(Same Stacktrace as above)
```

Here's my Debug Log.
[debug.log](https://github.com/SwanX1/SlightlyVanillaFlavoured/files/6497134/debug.log)

```

**Comment by evanbones** [comment]
That can be safely ignored, it's because a blank recipe file is included to disable crafting waystones
